#
# Copyright (c) 2026 PotterWhite
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
"""
Cookie Manager — automatic yt-dlp cookie renewal via Playwright + Chromium.

Health API:
  GET /health  → { status, last_refresh, cookie_age_hours, next_refresh }
  POST /refresh → trigger immediate cookie refresh

One-time setup: open noVNC at http://localhost:6901, log into YouTube.
After that, cookies auto-refresh every REFRESH_INTERVAL_HOURS (default: 6).
"""

import os
import json
import logging
import asyncio
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI
from fastapi.responses import JSONResponse

# ── Config ───────────────────────────────────────────────────────────────────
COOKIE_OUTPUT = os.getenv("COOKIE_OUTPUT", "/cookies/cookies.txt")
CHROME_PROFILE = os.getenv("CHROME_PROFILE", "/data/chrome-profile")
REFRESH_INTERVAL_HOURS = int(os.getenv("REFRESH_INTERVAL_HOURS", "6"))
# A public YouTube video to validate cookies (non-age-restricted, always available)
VALIDATION_VIDEO = os.getenv(
    "VALIDATION_VIDEO",
    "https://www.youtube.com/watch?v=jNQXAC9IVRw"  # "Me at the zoo" — first YT video
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger("cookie-manager")

app = FastAPI(title="Cookie Manager", docs_url=None, redoc_url=None)

# ── State ────────────────────────────────────────────────────────────────────
_state = {
    "last_refresh": None,       # ISO timestamp of last successful refresh
    "last_error": None,         # last error message (if any)
    "refresh_count": 0,         # total successful refreshes
    "is_refreshing": False,     # currently refreshing?
}


# ── Cookie refresh logic ─────────────────────────────────────────────────────

async def refresh_cookies() -> dict:
    """Visit youtube.com with persistent Chromium profile, export cookies.

    Returns dict with {success: bool, message: str, cookie_count: int}.
    """
    from playwright.async_api import async_playwright

    if _state["is_refreshing"]:
        return {"success": False, "message": "Refresh already in progress"}

    _state["is_refreshing"] = True
    try:
        log.info("Starting cookie refresh...")

        async with async_playwright() as p:
            # Launch Chromium with persistent profile (preserves login session)
            context = await p.chromium.launch_persistent_context(
                user_data_dir=CHROME_PROFILE,
                headless=True,
                args=[
                    "--no-sandbox",
                    "--disable-gpu",
                    "--disable-dev-shm-usage",
                ],
            )

            page = context.pages[0] if context.pages else await context.new_page()

            # Navigate to YouTube to refresh session cookies
            log.info("Navigating to youtube.com...")
            await page.goto("https://www.youtube.com", wait_until="domcontentloaded", timeout=30000)
            await page.wait_for_timeout(3000)  # let cookies settle

            # Export all cookies
            cookies = await context.cookies()
            await context.close()

        if not cookies:
            msg = "No cookies found — have you logged in via noVNC yet?"
            log.warning(msg)
            _state["last_error"] = msg
            return {"success": False, "message": msg, "cookie_count": 0}

        # Convert to Netscape cookie format
        lines = ["# Netscape HTTP Cookie File", "# Generated by ai_cookie_manager", ""]
        yt_cookie_count = 0
        for c in cookies:
            domain = c.get("domain", "")
            if "youtube" not in domain and "google" not in domain:
                continue
            yt_cookie_count += 1
            include_sub = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            expiry = int(c.get("expires", 0))
            name = c.get("name", "")
            value = c.get("value", "")
            lines.append(f"{domain}\t{include_sub}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")

        if yt_cookie_count == 0:
            msg = "No YouTube/Google cookies found — login may have expired"
            log.warning(msg)
            _state["last_error"] = msg
            return {"success": False, "message": msg, "cookie_count": 0}

        cookie_text = "\n".join(lines) + "\n"

        # Write to temp file first, then atomic rename
        tmp_path = COOKIE_OUTPUT + ".tmp"
        Path(tmp_path).parent.mkdir(parents=True, exist_ok=True)
        Path(tmp_path).write_text(cookie_text)

        # Validate: try a yt-dlp dry-run with the new cookies
        import subprocess
        proc = subprocess.run(
            ["yt-dlp", "--cookies", tmp_path, "--skip-download",
             "--no-warnings", "-q", VALIDATION_VIDEO],
            capture_output=True, text=True, timeout=30
        )

        if proc.returncode != 0:
            # Cookies may be invalid, but still write them (yt-dlp may fail for
            # other reasons like network issues). Log a warning.
            log.warning(f"Cookie validation returned exit code {proc.returncode}: "
                        f"{proc.stderr[:200] if proc.stderr else 'no stderr'}")

        # Atomic replace
        os.replace(tmp_path, COOKIE_OUTPUT)
        os.chmod(COOKIE_OUTPUT, 0o644)

        now = datetime.now(timezone.utc).isoformat()
        _state["last_refresh"] = now
        _state["last_error"] = None
        _state["refresh_count"] += 1

        log.info(f"Cookie refresh successful: {yt_cookie_count} YouTube/Google cookies exported")
        return {
            "success": True,
            "message": f"Exported {yt_cookie_count} cookies",
            "cookie_count": yt_cookie_count,
        }

    except Exception as e:
        msg = f"Cookie refresh failed: {str(e)}"
        log.error(msg)
        _state["last_error"] = msg
        return {"success": False, "message": msg, "cookie_count": 0}
    finally:
        _state["is_refreshing"] = False


# ── Background scheduler ─────────────────────────────────────────────────────

async def _scheduler_loop():
    """Refresh cookies periodically."""
    interval = REFRESH_INTERVAL_HOURS * 3600
    # Wait 30 seconds on startup for noVNC to be ready
    await asyncio.sleep(30)
    log.info(f"Cookie refresh scheduler started (every {REFRESH_INTERVAL_HOURS}h)")

    while True:
        try:
            result = await refresh_cookies()
            if not result["success"]:
                # Retry up to 3 times with backoff
                for attempt in range(1, 4):
                    wait = 60 * (2 ** attempt)  # 2m, 4m, 8m
                    log.info(f"Retry {attempt}/3 in {wait}s...")
                    await asyncio.sleep(wait)
                    result = await refresh_cookies()
                    if result["success"]:
                        break
        except Exception as e:
            log.error(f"Scheduler error: {e}")

        await asyncio.sleep(interval)


@app.on_event("startup")
async def start_scheduler():
    asyncio.create_task(_scheduler_loop())


# ── API endpoints ─────────────────────────────────────────────────────────────

@app.get("/health")
async def health():
    cookie_exists = Path(COOKIE_OUTPUT).is_file()
    cookie_age = None
    if cookie_exists:
        mtime = Path(COOKIE_OUTPUT).stat().st_mtime
        cookie_age = round((datetime.now(timezone.utc).timestamp() - mtime) / 3600, 1)

    return JSONResponse({
        "status": "healthy" if cookie_exists else "no_cookies",
        "cookie_file_exists": cookie_exists,
        "cookie_age_hours": cookie_age,
        "last_refresh": _state["last_refresh"],
        "last_error": _state["last_error"],
        "refresh_count": _state["refresh_count"],
        "is_refreshing": _state["is_refreshing"],
        "refresh_interval_hours": REFRESH_INTERVAL_HOURS,
    })


@app.post("/refresh")
async def trigger_refresh():
    """Manually trigger a cookie refresh."""
    result = await refresh_cookies()
    return JSONResponse(result)
